### ISSUE TITLE
Bug: opencollective: Permission denied

### ISSUE THREAD

**Issue by macjohnny** [opencollective/opencollective-postinstall#15]
## Issue Type
Bug

## Description
postinstall fails on CircleCI with the following error:

```
> opencollective postinstall

sh: 1: opencollective: Permission denied
wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! ng-packagr@4.4.5 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the ng-packagr@4.4.5 postinstall script.
```
https://circleci.com/gh/bithost-gmbh/ngx-mat-select-search/114?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Workaround
An easy workaround is to add the following to the `.circleci/config.yml`

```
jobs:
  build:
    ... 
    steps:
      ...
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
```

## Suggested fix
Don't throw errors if something fails, allowing to continue the installation without interruption.

## See also
https://github.com/ng-packagr/ng-packagr/issues/1178
